### ISSUE TITLE
Myanmar unicode

### ISSUE THREAD

**Issue by ThihaZaw-MM** [zawhtutwin/quizlab#3]
I run the program successfully. But, my computer only use Myanmar unicode not ZawGyi font. Should add supporting features for both Myanmar unicode and ZawGyi.

**Comment by zawhtutwin** [comment]
That's a good idea. Please create a patch for localization :+1:

**Comment by ThihaZaw-MM** [comment]
Thank you for assigning me for this issue I'll start doing it tonight.

**Comment by ThihaZaw-MM** [comment]
For unicode question and answer, should I add unicode text columns in question and answer table?

**Comment by ThihaZaw-MM** [comment]
Hello bro! I found a unicode converter and I'm working on it. But I should credit to original author of this converter class. By, using this converter, I don't need to add columns in database. Please suggest me which is better solution or if you have the best one?

**Comment by zawhtutwin** [comment]
One way is to seperate the message.json files
Example
http://plnkr.co/edit/NAaJ9v6kULqtuE0Vk2p4?p=info

Blog
http://blog.novanet.no/creating-multilingual-support-using-angularjs/

**Comment by ThihaZaw-MM** [comment]
Thanks bro! I'll try it.

**Comment by zawhtutwin** [comment]
Btw bro. According to your idea, it will be nice if we can add in feature to translate English to Myanmar directly using Google Translate API or something alike. :dancers:

**Comment by ThihaZaw-MM** [comment]
Hi bro @zawhtutwin ,
I'm ok with your example only in quizes page. When I try to modify the admin page and answer page, I cannot load the AdminController.js which is added by me. So, please suggest me how it would be done. If you want to check my code, I'll commit it without admin pages process.

**Comment by zawhtutwin** [comment]
Sure, bro just commit it. I will check :D

**Comment by ThihaZaw-MM** [comment]
I'm really sorry bro, when I commit my changes, the master branch was merged to my local and I carelessly push to master branch and got so many errors. I'm now trying to fix this and I do apologize for my careless mistakes.

**Comment by zawhtutwin** [comment]
ya, bro. I'm scratching my head to figure it out lolz. Pull the lastest
from the git first, then add in your change and commit to it. I will revert
the master to the previous version.

**Comment by ThihaZaw-MM** [comment]
ok thank you very much. I'm very sorry :(

**Comment by zawhtutwin** [comment]
don't worry, wait .. .I will let you know after the revert :D

**Comment by zawhtutwin** [comment]
ok now bro. I reverted back to "Add to Speech feature"

**Comment by zawhtutwin** [comment]
ok now bro I reverted back to "Add Text to Speech"

**Comment by zawhtutwin** [comment]
bro, let me know when you are finished :dancers:

**Comment by ThihaZaw-MM** [comment]
Sure bro, I'm working on it.

**Comment by ThihaZaw-MM** [comment]
Hello bro, I have some problem in QuizController.js. I used selected box in index.html for Unicode and Zawgyi fonts with ng-change event to trigger the QuizController font change process. Everything is going smooth as expected. But, it doesn't change anything even selectbox changed event was fired. After this, I placed the selectedbox in layout.html, it's working as expected. But, when I changed to 'ISTQB Exam 1 Mock Questions' to 'ISTQB Exam 2 Mock Questions', I couldn't hold the current value of selectbox. Please help me :P I'm new in angularjs and this would be the main problem :) :). Moreover, I cannot use controllers in .jsp pages.

**Comment by zawhtutwin** [comment]
Use html files(only) with angular. If there is no problem just commit it bro. I will take a look :)

**Comment by ThihaZaw-MM** [comment]
Committed bro! :)

**Comment by zawhtutwin** [comment]
sure I will check it out when I get back home :)

**Comment by zawhtutwin** [comment]
Yeah,bro. the thing you pointed out was right. I put the combobox inside ISQTB1 and ISQTB2 lolz. And about the switching to and fro between 1 and 2, I put   'reloadOnSearch: false' in the app.js. Addition to that there is a listener for 'routeUpdate' event inside the QuizController which will call the init function back again. That's pretty crazy coz if we don't call init there, questions from ISQTB1 will be appear in the ISQTB2 lolz btw if you have any other things/ideas you have in your mind, let me know.  :+1:
