### ISSUE TITLE
Unicode for question and answer data from database

### ISSUE THREAD

**Issue by ThihaZaw-MM** [zawhtutwin/quizlab#5]
![unicode](https://cloud.githubusercontent.com/assets/10017118/9664474/00c4dc58-5290-11e5-80b9-0e9b353c6489.png)
Hello bro, we did it :+1:  but we still have some issue to solve in unicode problems for question and answer from database. I want to convert them as user selected (unicode or zawgyi). As I mentioned earlier, I have a convertor class with java code to convert when the text loaded from database. But, this converter class was written by other developer and I want to add credit in this code. What is your idea?

**Comment by zawhtutwin** [comment]
It's a good idea. Of course we have to credit him. Let's do it then, you
make a head start development and let me be your help anytime :D

**Comment by zawhtutwin** [comment]
I think "listen" button defeat the purpose of the application. Since we are targeting to Myanmar users now, shall we remove that feature? what's yr idea ? :)

**Comment by ThihaZaw-MM** [comment]
Yeah bro, we should remove "listen" button because it cannot speak in Myanmar Language :)

**Comment by zawhtutwin** [comment]
I think I will do this do this feature this time bro. I think you are referring this class https://gist.github.com/trhura/b60ff85937d79812ddff   I see you are busying with SunShine :D

**Comment by ThihaZaw-MM** [comment]
Yeah completely right bro! I'm not busying with SunShine actually. I was on a trip and that's why I can't work :D

**Comment by zawhtutwin** [comment]
![unicode](https://cloud.githubusercontent.com/assets/91729/9720158/924cc32e-55b1-11e5-8543-5f92bb7442b7.png)

Adding the auto-conversion from Zawgyi to Unicode. Added a ConvertorController.java and Utils.java which is a helper to convert from Zawgyi to Unicode. From the client side "/quiz/getQuestionsByPackage/{packageName}/{font}" can be called. Font option is "zawgyi" and "unicode"

**Comment by ThihaZaw-MM** [comment]
Grate bro!! I'm also working on it. I'll stop now because you are done :+1:

**Comment by ThihaZaw-MM** [comment]
So, all we have to do now is to close this issue. We are done! Thank you :+1:

**Comment by zawhtutwin** [comment]
sure bro. Now closing it! :dancers:
