### ISSUE TITLE
To enable the support for unicode in admin module

### ISSUE THREAD

**Issue by zawhtutwin** [zawhtutwin/quizlab#6]
We will enable the unicode support in admin module.
![unicodesupport](https://cloud.githubusercontent.com/assets/91729/9725969/1f459b9c-5612-11e5-9040-c57fd7b5b02d.png)
Currently it support only ZawGyi

**Comment by ThihaZaw-MM** [comment]
OK bro. Let me try for it.

**Comment by zawhtutwin** [comment]
ok bro :+1:

**Comment by ThihaZaw-MM** [comment]
Hello bro! I'm done. Used linked instead of select box for font change process.

**Comment by zawhtutwin** [comment]
Very fast! But bro..Shall we try something like this? http://whatsinthemicrowave.com/?p=81  . message.properties style like you did in the angular. If you have difficulties, let me know. Push the :8ball:  back to you again lolz

**Comment by zawhtutwin** [comment]
Done!!!!
